# Generated by Django 4.1.3 on 2022-12-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hermana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('nacimiento', models.DateField()),
                ('edad', models.BooleanField()),
                ('profesion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Mama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('nacimiento', models.DateField()),
                ('edad', models.BooleanField()),
                ('profesion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Papa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('nacimiento', models.DateField()),
                ('edad', models.BooleanField()),
                ('profesion', models.CharField(max_length=20)),
            ],
        ),
    ]
