# Generated by Django 4.1.3 on 2022-12-14 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hermana',
            name='edad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mama',
            name='edad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='papa',
            name='edad',
            field=models.IntegerField(),
        ),
    ]
