# Generated by Django 4.1.3 on 2022-12-15 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_delete_hermana_delete_mama'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hermana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('nacimiento', models.DateField()),
                ('edad', models.IntegerField()),
                ('profesion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Madre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('nacimiento', models.DateField()),
                ('edad', models.IntegerField()),
                ('profesion', models.CharField(max_length=20)),
            ],
        ),
    ]
