# Generated by Django 4.1.3 on 2022-12-15 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_hermana_madre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hermana',
            name='profesion',
        ),
        migrations.RemoveField(
            model_name='madre',
            name='profesion',
        ),
        migrations.RemoveField(
            model_name='papa',
            name='profesion',
        ),
    ]
