# Generated by Django 4.1.3 on 2022-12-15 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0005_remove_hermana_profesion_remove_madre_profesion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hermana',
            name='nacimiento',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='madre',
            name='nacimiento',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='papa',
            name='nacimiento',
            field=models.CharField(max_length=20),
        ),
    ]
